CREATE table t_product_master (
	iproduct INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nm VARCHAR(100) NOT NULL,
	product_code VARCHAR(100) NOT NULL,
	rdt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	icpu INT UNSIGNED NOT NULL,
	igpu INT UNSIGNED NOT NULL,
	ram INT UNSIGNED NOT NULL,
	size INT UNSIGNED NOT NULL,
	weight INT UNSIGNED NOT NULL,
	brand VARCHAR(20) NOT NULL,
	os VARCHAR(20) NOT NULL,
	img VARCHAR(100)
);



CREATE TABLE t_product_cpu (
	icpu INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nm VARCHAR(20) NOT NULL,
	performance INT UNSIGNED NOT NULL,
	inner_gpu INT UNSIGNED NOT NULL,
	seq INT NOT NULL,
	brand VARCHAR(20) NOT NULL
);

CREATE TABLE t_product_gpu (
	igpu INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nm VARCHAR(20) NOT NULL,
	performance INT UNSIGNED NOT NULL,
	seq INT UNSIGNED NOT NULL,
	brand VARCHAR(20) NOT NULL
);

CREATE TABLE t_product_detail (
	idetail INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	iproduct INT UNSIGNED NOT NULL,
	color VARCHAR(20) NOT NULL,
	hdd INT UNSIGNED NOT NULL,
	ssd INT UNSIGNED NOT NULL,
	price INT UNSIGNED NOT NULL,
	stock INT UNSIGNED NOT NULL,
	isrep VARCHAR(1) NOT NULL CHECK (isrep IN('Y', 'N')),
	dc_rate FLOAT UNSIGNED NOT NULL,
	img VARCHAR(100) NOT NULL
);

CREATE TABLE t_product_question(
	iquestion INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	iproduct INT UNSIGNED NOT NULL,
	iuser INT UNSIGNED NOT NULL,
	ctnt VARCHAR(300) NOT NULL,
	rdt DATETIME DEFAULT CURRENT_TIMESTAMP,
	parent INT UNSIGNED NOT NULL
);

CREATE TABLE t_product_review(
	ireview INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	iproduct INT UNSIGNED NOT NULL,
	rating INT UNSIGNED NOT NULL,
	ctnt VARCHAR(300) NOT NULL,
	iuser INT UNSIGNED NOT NULL,
	rdt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE t_user(
	iuser INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	uid VARCHAR(20) NOT NULL,
	upw VARCHAR(300) NOT NULL,
	nm VARCHAR(5) NOT NULL,
	email VARCHAR(30) NOT NULL,
	rdt DATETIME DEFAULT CURRENT_TIMESTAMP,
	`point` INT UNSIGNED DEFAULT 0,
	role varchar(10) not null default 'ROLE_USER'
);

CREATE TABLE t_address(
	iaddress INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	iuser INT UNSIGNED NOT NULL,
	post VARCHAR UNSIGNED NOT NULL,
	addr VARCHAR(50) NOT NULL,
	addr_detail VARCHAR(50) NOT NULL,
	isrep VARCHAR(1) NOT NULL CHECK (isrep IN('Y', 'N'))
);

CREATE TABLE t_point (
	ipoint INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	iuser INT UNSIGNED NOT NULL,
	changed_point INT NOT NULL,
	rdt DATETIME DEFAULT CURRENT_TIMESTAMP,
	reason VARCHAR(50) NOT NULL
);

CREATE TABLE t_fav_mapping(
	iuser INT UNSIGNED NOT NULL,
	iproduct INT UNSIGNED NOT NULL,
	PRIMARY KEY(iuser, iproduct)
);

### 잘 몰라서 일단 뺌

###CREATE TABLE t_cart(
###	icart INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
###	iuser INT UNSIGNED NOT NULL
###);

###

CREATE TABLE t_cart(
	icart INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	iuser INT UNSIGNED NOT NULL,
	idetail INT UNSIGNED NOT NULL,
	quantity INT UNSIGNED NOT NULL
);

CREATE TABLE t_order (
	iorder INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	iuser INT UNSIGNED NOT NULL,
	spent_point INT UNSIGNED NOT NULL,
	payment_way VARCHAR(10) NOT NULL,
	result_price INT UNSIGNED NOT NULL,
	order_status VARCHAR(10) NOT NULL,
	rdt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	cdt DATETIME ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE t_order_product(
	iorder INT UNSIGNED NOT NULL,
	idetail INT UNSIGNED NOT NULL,
	quantity INT UNSIGNED NOT NULL,
	PRIMARY KEY(iorder, idetail)
);

CREATE TABLE t_program(
	iprogram INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nm VARCHAR(20) NOT NULL,
	required_cpu INT UNSIGNED NOT NULL, ### 수치
	required_gpu INT UNSIGNED NOT NULL, ### 수치
	required_ram INT UNSIGNED NOT NULL, ### 수치
	img VARCHAR(200) NOT NULL
);

CREATE TABLE t_question(
	iuser INT UNSIGNED NOT NULL
	# 질문 몇개 적어야함
);

CREATE TABLE t_program_question_mapping(
	iprogram INT UNSIGNED NOT NULL,
	iuser INT UNSIGNED NOT NULL
);

CREATE TABLE t_notice(
	inotice INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ctnt VARCHAR(500) NOT NULL,
	iadmin INT UNSIGNED NOT NULL,
	img VARCHAR(100),
	rdt DATETIME DEFAULT CURRENT_TIMESTAMP,
	hits INT UNSIGNED DEFAULT 0
);